// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA94odamd-ca-CjKzZRvqyVb-GGhjrGno',
    appId: '1:358714290872:web:553fd5356df1ce945f3a4d',
    messagingSenderId: '358714290872',
    projectId: 'emorhythm-be997',
    authDomain: 'emorhythm-be997.firebaseapp.com',
    storageBucket: 'emorhythm-be997.appspot.com',
    measurementId: 'G-DBH6V2D27W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTnuQeCtQzVa03_ayGBg_3bytOxgELrA',
    appId: '1:358714290872:android:fe1ce662ac9a59775f3a4d',
    messagingSenderId: '358714290872',
    projectId: 'emorhythm-be997',
    storageBucket: 'emorhythm-be997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnWlG4g4K7BGop0e4wZ2TnW3Mmiq-LatM',
    appId: '1:358714290872:ios:c43ef638a30c63d85f3a4d',
    messagingSenderId: '358714290872',
    projectId: 'emorhythm-be997',
    storageBucket: 'emorhythm-be997.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnWlG4g4K7BGop0e4wZ2TnW3Mmiq-LatM',
    appId: '1:358714290872:ios:6813a032543d13bd5f3a4d',
    messagingSenderId: '358714290872',
    projectId: 'emorhythm-be997',
    storageBucket: 'emorhythm-be997.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
